language: python
python:
- '3.6'
before_install:
- sudo apt-get install unzip
script:
- chmod +x zip.sh
- "./zip.sh"
before_deploy:
- git config --local user.name "TartaricAcid"
- git config --local user.email "baka943@qq.com"
- git tag "汉化资源包-Snapshot-$(date +'%Y%m%d%H%M%S')"
deploy:
  provider: releases
  api_key:
    secure: MqZT+Ib7I6z0f0TX3zKOVobZ8OTOezkWnMApDsRanZMzw+YdIsisZ1ES5cH/C0Sl8+YGZYRbsrm2E5cVKS9ZbRyd3B4hKJbWWlLNkJm0fOR2fbmyEcu8dZiVOIWWDez4fI/H1q5353QrnxtzBHClaELx+IzGCj5SvKRiPXQqgm1tIw5vCOOb+PFvBo5N95/iAnET0SYxfcJDsU4uB9mB4WpoyL8oxoH0rSWWxbx+VGBH7MRtRm9vvMEb57GB5IPLgPEAKt3Sycxc7WzBVfcrjA4VbE+MuMkU4BrBQLT7VLYoknEiDoyd4gDNwGoskWR6DQytvS5hHB/iqEsm/AsTdULEJ0dqCYD1mgt+u3y+R8r2THh4lOk8nGlizM91jKffYE3JcI7fYc1nz9XDIrJ0e9sKkkjmpRUpOi4LEw7vwCr4ToKGSexCWuJDJCw1msQYiG/ElsH9Gs2qIdVqpg2mm1SsQ8x1yThPzZgtH3Vbmnn6ztVhfipoxzOhyzoCUqHra794EPW3QBa3aFwAj/mmR+5fYrka0OMwpl+r9Of6pC/+SnAieaY4jM3DyFJ0axpmMhHfCVwNxM8FxtEz8NieQnmFzI8WOiNxAmxroit2tfkqGDW6mU985CETAAaiq0cv34NoKjYI/HjwUe/uZyhmTdsN7TbTsdw60QCEP+hHSLs=
  file: Minecraft-Mod-Language-Modpack.zip
  on:
    repo: CFPAOrg/Minecraft-Mod-Language-Package
    branch: 1.12.2
