language: python
python:
  - '3.6'
script:
  - "python3 ./zip.py"
before_deploy:
  - git config --local user.name "TartaricAcid"
  - git config --local user.email "baka943@qq.com"
  - git tag "汉化资源包-Snapshot-$(date +'%Y%m%d%H%M%S')"
deploy:
  provider: releases
  api_key:
    secure: KmeoGPGKBYjliQomtTeynl6Q42m/3k9jf/2FY6qu8fX8uqA4RhgZsdphP9PZ1WkKNds80H9p7zSAc57l8qrPkLoyYOfJGRiZZB68G6/AKKV0xTm4SV/6ItoTa7sSQkFNr1U1UBdvDiC7RRpPWMyVwxFefT5GWxg15/+O5DNkAgMwn4/Ea0l5q358Rgod3WkdKeLT3QPrEjY+8lUUlC4edYwVJhe2U/pAHcDkOGQJQX+JAVd+ss6QHK4FAk0vFm0demIT2/ByPkqmajo5M1vSLFnhoOMJdyIeNKeZGslydAgUGf3AQCn7VoPV4zBa3+q2sEEVDVMZkp2HjxgYBfzk9M00EJ78ETryIetpa6r7rVPz+rxAVyzJqdhCH4/TqCA+a6j0j/axqqyVNfPqqU2wPEgCindvU9hMjJ3y1be6gmElGdDP0uDab3/lGUWiZdwFr32G732QA7LV+ZeTABAuhCoOz9WAFMN4mDI7dwPn67D2FEfa/Q6e7aiaEG0A/M90bqlKs0bkhubNczJJgl2s2FXKsHzPLU7GXRlT6kgt1I7WzTBMuGvHrqJ5mBGNCQMsELjAoZuzskqbvsdqzgDF8VUj+n2VSMYQzksBK0+g8lJ9eH2KWr1MRPekENaQf47Xh9T1BPTsf3Hcu9xwcNhneUYyTgBol3Pg3PjqRFdrO2Y=
  file:
    - "Minecraft-Mod-Language-Modpack.zip"
  skip_cleanup: true
  on:
    repo: CFPAOrg/Minecraft-Mod-Language-Package
    branch: 1.12.2
