# 爬虫工具的配置文件

# 爬虫抓取的版本
# 目前只有 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11.2, 1.12.2 四个可选
version: 1.12.2

# 爬虫的线程数
threads_num: 20

# 爬虫的爬取页数
mod_page: 30
modpack_page: 1

# 爬虫白名单，在此名单上的模组和整合包会被爬取
# 名单请使用 curseforge url 中的名称
mod_whitelist:
  - integrated-rest
modpack_whitelist:
  - baka943

# 爬虫黑名单，在此名单上的模组和整合包会被禁止爬取，会覆盖白名单
# 名单请使用 curseforge url 中的名称
mod_blacklist:
  - dungeon-tactics
  - minecraft-comes-alive-mca
  - bookshelf
  - mike-dongles
  - magical-psi
modpack_blacklist:
  - the-new-frontier
