# 爬虫工具的配置文件

# 爬虫抓取的版本
# 目前只有 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11.2, 1.12.2 四个可选
version: 1.12.2

# 爬虫的线程数
threads_num: 20

# 爬虫的爬取页数
mod_page: 30
modpack_page: 1

# 爬虫白名单，在此名单上的模组和整合包会被爬取
# 名单请使用 curseforge url 中的名称
mod_whitelist:
  - integrated-rest
  - automated-redstone
  - inspirations
  - teletoro
  - simulated-nights
  - mrcrayfishs-device-mod
  - mrcrayfishs-jumping-castle-mod
  - dab-mod
modpack_whitelist:

# 爬虫黑名单，在此名单上的模组和整合包会被禁止爬取，会覆盖白名单
# 名单请使用 curseforge url 中的名称
mod_blacklist:
  - dungeon-tactics
  - minecraft-comes-alive-mca
  - bookshelf
  - mike-dongles
  - magical-psi
  - the-twilight-forest
  - charset-lib
modpack_blacklist:
  - the-new-frontier

# del list 名单，用于清除不需要提交的 assets 文件
# 需要写入对应的 assets 文件名，不是 url 名称
del_list:
  - writing_guides
  - chisel_guide
  - pokecube_books

# 邮件发送提醒
# 按次序写入需要发送的邮箱
email:
  - baka943@qq.com
  - baka943@163.com
