name: Spider

on:
  schedule:
  - cron: "0 */8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.3

    # Runs a single command using the runners shell
    - name: Run spider
      run: ./spider.ps1
      shell: pwsh
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
      
